### ISSUE TITLE
Poderia ter um define para indicar o que é cada state

### ISSUE THREAD

**Issue by eduardomarossi** [vitorsv1/aps2-embarcados#1]
https://github.com/vitorsv1/aps2-embarcados/blob/03565acdfa4332bde43b381781f0424149830650/Maquina%20de%20Lavar%20-%20LCD/MXT_EXAMPLE_USART1/src/main.c#L293-L297

#define CLICKED 1
#define RELEASED 2

etc

**Comment by vitorsv1** [comment]
Resolvido em no commit ff5a74de72b0f40b45a554d43957e928d2b8f183
