### ISSUE TITLE
Código morto / comentado

### ISSUE THREAD

**Issue by eduardomarossi** [vitorsv1/aps2-embarcados#3]
https://github.com/vitorsv1/aps2-embarcados/blob/03565acdfa4332bde43b381781f0424149830650/Maquina%20de%20Lavar%20-%20LCD/MXT_EXAMPLE_USART1/src/main.c#L360-L382

Ideal é remover, se precisar recuperar, restaurar via git

**Comment by vitorsv1** [comment]
#10
