### ISSUE TITLE
Cenário 1 satisfaz parcialmente, é apenas apertar na tela pra travar/destravar tela, para travar tudo bem, mas o destrave é simples demais. 

### ISSUE THREAD

**Issue by eduardomarossi** [vitorsv1/aps2-embarcados#7]

**Comment by juanjorgegarcia** [comment]
Issue resolvido no commit "lock consertado" (371cfdeebdc247897daf6d3f45b4fb426ed49188), agora o display é travado/destravado somente após o usuário apertar e segurar no botão lock por mais de 3 segundos.
